name: Deploy Artifacts

on:
  workflow_dispatch:
  push:
    branches: [ "main", "feature/*" ]
    tags: [ '*.*.*' ]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup
    steps:
      - name: Setup
        run: |
          echo "Setup Deploy!"
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy Things
        run: |
          echo "Deploying Things!"
